version: '3.8'
services:
  traefik:
    image: traefik:v2.11
    command:
      - --api.dashboard=true
      - --api.insecure=true
      - --entrypoints.web.address=:80
      - --providers.docker.swarmMode=true
      - --providers.docker.exposedByDefault=false
      - --providers.docker.network=net-public
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 8080
        published: 8080
        mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - net-public
    deploy:
      placement:
        constraints:
          - node.labels.role==manager
  api-gateway:
    image: 10.100.12.105:5000/api-gateway:v1
    networks:
      - net-public
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.api.rule=PathPrefix(`/`)
        - traefik.http.services.api.loadbalancer.server.port=3000
  user-service:
    image: 10.100.12.105:5000/user-service:v1
    networks:
      - net-public
    deploy: {}
  post-service:
    image: 10.100.12.105:5000/post-service:v1
    networks:
      - net-public
    deploy:
      replicas: 3
  media-service:
    image: 10.100.12.105:5000/media-service:v1
    networks:
      - net-public
    deploy: {}
  notification-service:
    image: 10.100.12.105:5000/notification-service:v1
    networks:
      - net-public
    deploy: {}
networks:
  net-public:
    external: true
